### ISSUE TITLE
ClientboundSoundPacket deserialization failure when sent by playsound

### ISSUE THREAD

**Issue by allinkdev** [mat-1/azalea#89]
Executing commands like `execute as <azalea bot> at @s run playsound minecraft:ambient.cave master @s ~ ~ ~` will cause a deserialization error in ClientboundSoundPacket.

Error:
```Error reading packet from Client: LeftoverData { data: [0, 0, 2, 48, 255, 255, 255, 244, 63, 128, 0, 0, 63, 128, 0, 0, 63, 103, 41, 228, 92, 95, 200, 35], packet_name: "ClientboundSoundPacket" }    ```

**Comment by mat-1** [comment]
Thanks for reporting, fixed :)

The issue came from Mojang changing ClientboundSoundPacket to be able to fall back to a ResourceLocation in 1.19.3-rc1 and me not noticing that change.

**Comment by allinkdev** [comment]
Thanks for the fast response & fix!
